repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: check-merge-conflict
    - id: check-ast
    - id: flake8
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: check-symlinks
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: check-added-large-files
