# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\brreader\design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1040, 810)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.MainLayout = QtWidgets.QHBoxLayout()
        self.MainLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.MainLayout.setObjectName("MainLayout")
        self.MainInfoLayout = QtWidgets.QVBoxLayout()
        self.MainInfoLayout.setObjectName("MainInfoLayout")
        self.ProductInfo = QtWidgets.QGridLayout()
        self.ProductInfo.setObjectName("ProductInfo")
        self.StorageType = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.StorageType.setFont(font)
        self.StorageType.setAlignment(QtCore.Qt.AlignCenter)
        self.StorageType.setObjectName("StorageType")
        self.ProductInfo.addWidget(self.StorageType, 1, 0, 1, 1)
        self.Packaging = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Packaging.setFont(font)
        self.Packaging.setAlignment(QtCore.Qt.AlignCenter)
        self.Packaging.setObjectName("Packaging")
        self.ProductInfo.addWidget(self.Packaging, 1, 1, 1, 1)
        self.Weight = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.Weight.setFont(font)
        self.Weight.setAlignment(QtCore.Qt.AlignCenter)
        self.Weight.setObjectName("Weight")
        self.ProductInfo.addWidget(self.Weight, 2, 0, 1, 2)
        self.Name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Name.setFont(font)
        self.Name.setAlignment(QtCore.Qt.AlignCenter)
        self.Name.setObjectName("Name")
        self.ProductInfo.addWidget(self.Name, 0, 0, 1, 2)
        self.MainInfoLayout.addLayout(self.ProductInfo)
        self.ButtonGrid = QtWidgets.QGridLayout()
        self.ButtonGrid.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ButtonGrid.setContentsMargins(25, 25, 25, 25)
        self.ButtonGrid.setHorizontalSpacing(25)
        self.ButtonGrid.setVerticalSpacing(10)
        self.ButtonGrid.setObjectName("ButtonGrid")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.ButtonGrid.addWidget(self.clearButton, 1, 0, 1, 1)
        self.openDbButton = QtWidgets.QPushButton(self.centralwidget)
        self.openDbButton.setObjectName("openDbButton")
        self.ButtonGrid.addWidget(self.openDbButton, 0, 0, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.ButtonGrid.addWidget(self.saveButton, 0, 1, 1, 1)
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.ButtonGrid.addWidget(self.exitButton, 1, 1, 1, 1)
        self.MainInfoLayout.addLayout(self.ButtonGrid)
        self.MainLayout.addLayout(self.MainInfoLayout)
        self.BarcodeHistory = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BarcodeHistory.setFont(font)
        self.BarcodeHistory.setObjectName("BarcodeHistory")
        self.MainLayout.addWidget(self.BarcodeHistory)
        self.MainLayout.setStretch(0, 4)
        self.MainLayout.setStretch(1, 3)
        self.gridLayout.addLayout(self.MainLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1040, 26))
        self.menubar.setObjectName("menubar")
        self.settings = QtWidgets.QMenu(self.menubar)
        self.settings.setObjectName("settings")
        self.menuCOM = QtWidgets.QMenu(self.settings)
        self.menuCOM.setObjectName("menuCOM")
        self.database = QtWidgets.QMenu(self.menubar)
        self.database.setObjectName("database")
        self.file = QtWidgets.QMenu(self.menubar)
        self.file.setObjectName("file")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.no_ports = QtWidgets.QAction(MainWindow)
        self.no_ports.setEnabled(False)
        self.no_ports.setObjectName("no_ports")
        self.actiontest2 = QtWidgets.QAction(MainWindow)
        self.actiontest2.setObjectName("actiontest2")
        self.loadDb = QtWidgets.QAction(MainWindow)
        self.loadDb.setObjectName("loadDb")
        self.reloadDb = QtWidgets.QAction(MainWindow)
        self.reloadDb.setObjectName("reloadDb")
        self.save = QtWidgets.QAction(MainWindow)
        self.save.setObjectName("save")
        self.clear = QtWidgets.QAction(MainWindow)
        self.clear.setObjectName("clear")
        self.openDb = QtWidgets.QAction(MainWindow)
        self.openDb.setObjectName("openDb")
        self.menuCOM.addAction(self.no_ports)
        self.settings.addAction(self.menuCOM.menuAction())
        self.database.addAction(self.openDb)
        self.database.addAction(self.loadDb)
        self.database.addAction(self.reloadDb)
        self.file.addAction(self.save)
        self.file.addAction(self.clear)
        self.menubar.addAction(self.file.menuAction())
        self.menubar.addAction(self.settings.menuAction())
        self.menubar.addAction(self.database.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BarcodeScanner101"))
        self.StorageType.setText(_translate("MainWindow", "Вид хранения"))
        self.Packaging.setText(_translate("MainWindow", "Вид упаковки"))
        self.Weight.setText(_translate("MainWindow", "0, 000 г"))
        self.Name.setText(_translate("MainWindow", "Наименование"))
        self.clearButton.setText(_translate("MainWindow", "Очистить"))
        self.openDbButton.setText(_translate("MainWindow", "Загрузить файл базы"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить отчет"))
        self.exitButton.setText(_translate("MainWindow", "Выход"))
        self.settings.setTitle(_translate("MainWindow", "Настройки"))
        self.menuCOM.setTitle(_translate("MainWindow", "COM порт"))
        self.database.setTitle(_translate("MainWindow", "База"))
        self.file.setTitle(_translate("MainWindow", "Файл"))
        self.no_ports.setText(_translate("MainWindow", "(нет доступных портов)"))
        self.actiontest2.setText(_translate("MainWindow", "test2"))
        self.loadDb.setText(_translate("MainWindow", "Загрузить"))
        self.reloadDb.setText(_translate("MainWindow", "Обновить"))
        self.save.setText(_translate("MainWindow", "Сохранить"))
        self.clear.setText(_translate("MainWindow", "Очистить"))
        self.openDb.setText(_translate("MainWindow", "Изменить"))
